config:
  player:
    hp: 20
    mass: 750
    drag: 0.2
    topSpeed: 6
    accel: 0.8
  playerPart:
    hp: 20
    mass: 3000
    drag: 0
    bounce: 1
    gunOffsetX: 0
    gunOffsetY: -10
    gunOffsetNoise: 5
    partWingCandidates:
      - key: spaceshooterExt
        frame: spaceParts_001
      - key: spaceshooterExt
        frame: spaceParts_002
      - key: spaceshooterExt
        frame: spaceParts_003
      - key: spaceshooterExt
        frame: spaceParts_004
      - key: spaceshooterExt
        frame: spaceParts_005
      - key: spaceshooterExt
        frame: spaceParts_006
      - key: spaceshooterExt
        frame: spaceParts_007
      - key: spaceshooterExt
        frame: spaceParts_008
      - key: spaceshooterExt
        frame: spaceParts_009
    partGunCandidates:
      - key: spaceshooter
        frame: gun08
  enemy:
    hp: 6
    mass: 3000
    drag: 0
    shootRate: 1000
    bulletSpeed: 3.5
    bowOutTime: 20 # seconds
    # spawnInterval: 1000
  difficultyCurve:
    - { wait: 0, desc: 'init', allowedEnemies: 2, enemySpawnInterval: 1500, enemyHP: 6 }
    - { wait: 5000, desc: '', allowedEnemies: 3, enemySpawnInterval: 1300, enemyHP: 7 }
    - { wait: 15000, desc: '', allowedEnemies: 4, enemySpawnInterval: 1000, enemyHP: 8 }
    - { wait: 10000, desc: '', allowedEnemies: 5, enemySpawnInterval: 1000, enemyHP: 8 }
    - { wait: 8000, desc: '', allowedEnemies: 5, enemySpawnInterval: 1000, enemyHP: 9 }
    - { wait: 5000, desc: '', allowedEnemies: 7, enemySpawnInterval: 800, enemyHP: 11 }
    - { wait: 7000, desc: '', allowedEnemies: 9, enemySpawnInterval: 700, enemyHP: 15 }
    - { wait: 10000, desc: '', allowedEnemies: 12, enemySpawnInterval: 500, enemyHP: 15 }
    - { wait: 10000, desc: '', allowedEnemies: 12, enemySpawnInterval: 500, enemyHP: 17 }
    - { wait: 10000, desc: '', allowedEnemies: 15, enemySpawnInterval: 700, enemyHP: 19 }
    - { wait: 10000, desc: '', allowedEnemies: 15, enemySpawnInterval: 700, enemyHP: 19 }
    - { wait: 20000, desc: 'end', end: true }