config:
  player:
    hp: 20
    mass: 750
    drag: 0.2
    topSpeed: 6
    accel: 0.8
  playerPart:
    hp: 20
    mass: 3000
    drag: 0
    bounce: 1
    gunOffsetX: 0
    gunOffsetY: -10
    gunOffsetNoise: 5
    partWingCandidates:
      - key: spaceshooterExt
        frame: spaceParts_001
      - key: spaceshooterExt
        frame: spaceParts_002
      - key: spaceshooterExt
        frame: spaceParts_003
      - key: spaceshooterExt
        frame: spaceParts_004
      - key: spaceshooterExt
        frame: spaceParts_005
      - key: spaceshooterExt
        frame: spaceParts_006
      - key: spaceshooterExt
        frame: spaceParts_007
      - key: spaceshooterExt
        frame: spaceParts_008
      - key: spaceshooterExt
        frame: spaceParts_009
    partGunCandidates:
      - key: spaceshooterExt
        frame: gun08
  enemy:
    hp: 6
    mass: 3000
    drag: 0
    shootRate: 1000
    bulletSpeed: 3.5
    bowOutTime: 20 # seconds
    # spawnInterval: 1000